# Generated by Django 4.0.1 on 2022-10-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_profile_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkedbook',
            old_name='ha_returned',
            new_name='has_returned',
        ),
    ]
