# Generated by Django 4.0.1 on 2022-10-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_ha_returned_checkedbook_has_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/'),
        ),
    ]
